[build]
  base = "bettersurallah"
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://zxqpkcvirsddvbvkiqcj.supabase.co"
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ln8Imc36zVI1jymTciA56A_RjMs83rp"
