insert into public.projects (title, barangay, amount, funding_source, year, status, description) values
('Construction of Potable Water System', 'Buenavista', 1500000.00, 'BUB', 2014, 'completed', 'Bottom-Up Budgeting (BUB) - Water Supply'),
('Upgrading of NACI Water System', 'Naci', 500000.00, 'BUB', 2015, 'completed', 'Bottom-Up Budgeting (BUB) - Water Supply'),
('Construction of Potable Water System', 'Moloy', 1350000.00, 'BUB', 2015, 'completed', 'Bottom-Up Budgeting (BUB) - Water Supply'),
('Construction of Potable Water System', 'Talahik', 1350000.00, 'BUB', 2015, 'completed', 'Bottom-Up Budgeting (BUB) - Water Supply'),
('Construction of Potable Water System Level II', 'Tubi-Ala', 2000000.00, 'LGSF', 2014, 'completed', 'LGSF - Sagana at Ligtas na Tubig para sa Lahat (SALINTUBIG)'),
('Road Project in Purok Matinong-San Jose Road', 'Dajay', 1880000.00, 'BUB', 2014, 'completed', 'Bottom-Up Budgeting (BUB) - Local Access Road'),
('Concreting of Colongulo-Buenavista Road', 'Colongulo', 1300000.00, 'LGSF', 2016, 'completed', 'LGSF - Roads & Bridges'),
('Construction of Rosas-Moloy Road', 'Moloy', 2750000.00, 'LGSF', 2016, 'completed', 'LGSF - Roads & Bridges'),
('Construction of Potable Water System', 'Colongulo', 1000000.00, 'ADM', 2017, 'completed', 'Assistance to Disadvantaged Municipalities (ADM) - Water'),
('Construction of Potable Water System', 'Upper Sepaka', 2000000.00, 'ADM', 2017, 'completed', 'ADM - Water'),
('Concreting of Road', 'Moloy', 5000000.00, 'ADM', 2017, 'completed', 'ADM - Roads'),
('Concreting of Road', 'Talahik', 5000000.00, 'ADM', 2017, 'completed', 'ADM - Roads'),
('Concreting of Road', 'Libertad', 4066000.00, 'ADM', 2017, 'completed', 'ADM - Roads'),
('Local Access Road', 'Libertad', 7072500.00, 'AM', 2018, 'completed', 'Assistance to Municipalities (AM) - Local Access'),
('Local Access Road', 'Libertad', 2679500.00, 'AM', 2018, 'completed', 'AM - Local Access'),
('Local Access Road', 'Libertad', 1807501.00, 'AM', 2018, 'completed', 'AM - Local Access'),
('Local Access Road in Narra Street', 'Libertad', 6819600.00, 'AM', 2019, 'completed', 'AM - Local Access'),
('Local Road Access in Malvar Street', 'Libertad', 5887400.00, 'AM', 2019, 'completed', 'AM - Local Access'),
('Upgrading of PWS Level II to Level III', 'Moloy', 3500000.00, 'LGSF', 2020, 'ongoing', 'LGSF - SALINTUBIG'),
('Construction of Potable Water System Level II in Purok 2', 'Duengas', 5425820.00, 'LGSF', 2020, 'ongoing', 'LGSF - SALINTUBIG'),
('Construction of Potable Water System Level II at Lubol', 'Sepaka', 2898302.00, 'LGSF', 2020, 'ongoing', 'LGSF - SALINTUBIG'),
('Upgrading of Pardo de Tavera Street', 'Libertad', 11897000.00, 'AM', 2020, 'ongoing', 'AM - Local Access');

insert into public.documents (title, category, year, source_url, description) values
('LGU Surallah Citizen''s Charter 2026 (1st edition)', 'citizens_charter', 2026, 'https://surallah.gov.ph/wp-content/uploads/2026/03/LGU-Surallah-Citizens-charter-2026-1st-edition_compressed.pdf', null),
('LGU Surallah Certificate of Compliance (COC) 2026', 'citizens_charter', 2026, 'https://surallah.gov.ph/wp-content/uploads/2026/03/LGU-SURALLAH-COC-2026.pdf', null),
('LGU Surallah Citizen''s Charter 2025', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/03/LGU-SURALLAH-CITIZEN-CHARTER-2025-.pdf', null),
('LGU Surallah Certificate of Compliance (COC) 2025', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/03/LGUSURALLAH_COC_20250328.pdf', null),
('LGU Surallah Citizen''s Charter Handbook 2024', 'citizens_charter', 2024, 'https://surallah.gov.ph/wp-content/uploads/2024/04/LGU-Surallah-Citizens-Charter-Handbook-2024.pdf', null),
('LGU Surallah Certificate of Compliance (COC) 2024', 'citizens_charter', 2024, 'https://surallah.gov.ph/wp-content/uploads/2024/10/SURALLAH_COC_20240404.pdf', null),
('Citizen''s Charter — Brgy. Buenavista', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/BUENAVESTA.pdf', null),
('COC — Brgy. Buenavista', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Buenavesta-COC.pdf', null),
('Citizen''s Charter — Brgy. Canahay', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/CANAHAY.pdf', null),
('COC — Brgy. Canahay', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/canahay-COC.pdf', null),
('Citizen''s Charter — Brgy. Centrala', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/CENTRALA.pdf', null),
('COC — Brgy. Centrala', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Centrala-COC.pdf', null),
('Citizen''s Charter — Brgy. Colongulo', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/COLONGULO-.pdf', null),
('COC — Brgy. Colongulo', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Colongulo-COC.pdf', null),
('Citizen''s Charter — Brgy. Dajay', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/DAJAY.pdf', null),
('COC — Brgy. Dajay', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/DAJAY.COC_.pdf', null),
('Citizen''s Charter — Brgy. Duengas', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/DUENGAS.pdf', null),
('COC — Brgy. Duengas', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Duengas-COC.pdf', null),
('Citizen''s Charter — Brgy. Lambontong', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LAMBONTONG.pdf', null),
('Citizen''s Charter — Brgy. Lamian', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LAMIAN.pdf', null),
('COC — Brgy. Lamian', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LAMIAN-COC.pdf', null),
('Citizen''s Charter — Brgy. Lamsugod', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LAMSUGOD.pdf', null),
('COC — Brgy. Lamsugod', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LAMSUGOD-COC.pdf', null),
('Citizen''s Charter — Brgy. Libertad', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LIBERTAD1.pdf', null),
('COC — Brgy. Libertad', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Libertad.COC_.pdf', null),
('Citizen''s Charter — Brgy. Little Baguio', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/LITTLE-BAGUIO.pdf', null),
('Citizen''s Charter — Brgy. Moloy', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/MOLOY.pdf', null),
('COC — Brgy. Moloy', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/moloy-COC.pdf', null),
('Citizen''s Charter — Brgy. Naci', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/NACI.pdf', null),
('COC — Brgy. Naci', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/NACI-COC.pdf', null),
('Citizen''s Charter — Brgy. Talahik', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/TALAHIK.pdf', null),
('Citizen''s Charter — Brgy. Tubi-Alah', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/TUBI-ALAH.pdf', null),
('COC — Brgy. Tubi-Alah', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Tubi-alah-COC.pdf', null),
('Citizen''s Charter — Brgy. Upper Sepaka', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/UPPER-SEPAKA.pdf', null),
('COC — Brgy. Upper Sepaka', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/Upper-sepaka-COC.pdf', null),
('Citizen''s Charter — Brgy. Veterans', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/VETERANS.pdf', null),
('COC — Brgy. Veterans', 'citizens_charter', 2025, 'https://surallah.gov.ph/wp-content/uploads/2025/06/VETERANS-COC.pdf', null);
